version: 0.7.{build}

image: Visual Studio 2017

platform: 
 - x86
 - x64

configuration:
 - Debug

clone_folder: c:\editor

environment:
  QTDIR: C:\Qt\6.0.1\msvc2019_64
  PATH: %PATH%;%QT_DIR%\bin

install:
 - dir C:\Qt\6.0.1\msvc2019_64
 - git submodule update --init --recursive


build_script:
 - mkdir build
 - cd build
 - echo %platform%
 - echo %APPVEYOR_BUILD_NUMBER%
 - if %platform%==x64 (cmake .. -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DCI_PROVIDER=AppVeyor -G "Visual Studio 15 2017 Win64")
 - if %platform%==x86 (cmake .. -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DCI_PROVIDER=AppVeyor -G "Visual Studio 15 2017")
 - cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


test: off
