version: 0.7.{build}

image: Visual Studio 2017

platform: 
 - x86
 - x64

configuration:
 - Debug

clone_folder: c:\editor

build_script:
 - mkdir build
 - cd build
 - echo %platform%
 - echo %APPVEYOR_BUILD_NUMBER%
 - if %platform%==x64 (cmake .. -DSDL2_DIR=c:\relive\SDL2-2.0.9 -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DCI_PROVIDER=AppVeyor -G "Visual Studio 15 2017 Win64")
 - if %platform%==x86 (cmake .. -DSDL2_DIR=c:\relive\SDL2-2.0.9 -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DCI_PROVIDER=AppVeyor -G "Visual Studio 15 2017")
 - cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

install:
 - git submodule update --init --recursive

test: off
