version: 0.7.{build}

image: Visual Studio 2019

platform: 
 - x86
 - x64

configuration:
 - Debug

clone_folder: c:\editor

install:
 - dir C:\Qt\5.15.2\msvc2019_64
 - git submodule update --init --recursive


build_script:
 - mkdir build
 - cd build
 - echo %platform%
 - echo %APPVEYOR_BUILD_NUMBER%
 - set QT_DIR=C:\Qt\5.15.2\msvc2019_64
 - set PATH=%PATH%;%QT_DIR%;%QT_DIR%\bin
 - echo %PATH%
 - if %platform%==x64 (cmake .. -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DCI_PROVIDER=AppVeyor -G "Visual Studio 16 2019 Win64")
 - if %platform%==x86 (cmake .. -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DCI_PROVIDER=AppVeyor -G "Visual Studio 16 2019")
 - cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


test: off
