
trigger:
- master

jobs:

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
        brew install qt5
        echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile
        git submodule update --init
        cmake --version
        mkdir build
        cd build
        cmake -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 -DBUILD_NUMBER=$(Build.BuildId) -G"Unix Makefiles" ..
        make -j4
