
trigger:
- master

jobs:

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
        brew install qt5
        export LDFLAGS="-L/usr/local/opt/qt@5/lib"
        export CPPFLAGS="-I/usr/local/opt/qt@5/include"
        export QT_DIR=/usr/local/opt/qt@5
        git submodule update --init
        cmake --version
        mkdir build
        cd build
        cmake -DBUILD_NUMBER=$(Build.BuildId) -G"Unix Makefiles" ..
        make -j4
