
trigger:
- master

jobs:

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
        brew install brew install qt5
        git submodule update --init
        cmake --version
        mkdir build
        cd build
        cmake -DBUILD_NUMBER=$(Build.BuildId) -G"Unix Makefiles" ..
        make -j4
