
trigger:
- master

jobs:

- job: Windows32
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
        git submodule update --init
        pip install aqtinstall
        aqt list-qt windows desktop --arch 5.15.2
        mkdir Qt
        cd Qt
        aqt install-qt windows desktop 5.15.2 win32_msvc2019
        cd ..
        cd build
        mkdir build
        cd build
        dir $(Build.SourcesDirectory)\Qt\5.15.2\msvc2019
        cmake .. -DQt5_DIR="$(Build.SourcesDirectory)\Qt\5.15.2\msvc2019" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_NUMBER=$(Build.BuildId) -G "Visual Studio 16 2019" -A Win32
        cmake --build .
