
trigger:
- master

jobs:

- job: Windows32
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
        git submodule update --init
        pip install aqtinstall
        aqt list-qt windows desktop --arch 6.2.0
        mkdir Qt
        cd Qt
        aqt install-qt windows desktop 5.15.2 win64_msvc2019_32 -m qtmultimedia
        cd ..
        cd build
        mkdir build
        cd build
        cmake .. DQt5_DIR=c:\Qt\5.15.2 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_NUMBER=$(Build.BuildId) -G "Visual Studio 16 2019" -A Win32
        cmake --build .
