
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
        sudo apt-get update
        sudo apt-get install qtdeclarative5-dev
        sudo apt-get install qtmultimedia5-dev
        sudo apt-get install qttools5-dev
        git submodule update --init
        cmake --version
        mkdir build
        cd build
        cmake -DBUILD_NUMBER=$(Build.BuildId) -G"Unix Makefiles" ..
        make -j4
