name: CI

on: [push, pull_request]

# build setting(s)
env:
  CONFIGURATION: Release

jobs:
  build-windows32:
    runs-on: windows-latest
    name: Windows32

    steps:
    - name: Checkout repository recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Install Qt 5.15.2'
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'win32_msvc2019'

    - name: 'Build'
      run: |
        mkdir build
        cd build
        cmake -S .. -B . -G"Visual Studio 17 2022" -DCMAKE_PREFIX_PATH="$env:QT_ROOT_DIR" -A Win32
        cmake --build . --config $env:CONFIGURATION
        cd $env:CONFIGURATION
        mkdir deploy
        move qt-editor.exe ./deploy
        windeployqt ./deploy/qt-editor.exe --no-translations --no-system-d3d-compiler --no-angle --no-opengl-sw --no-svg --dir ./deploy --plugindir ./deploy/plugins

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: Windows32-${{ env.CONFIGURATION }}-qt-editor
        path: build\${{ env.CONFIGURATION }}\deploy

  build-windows64:
    runs-on: windows-latest
    name: Windows64
  
    steps:
    - name: Checkout repository recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Install Qt 5.15.2'
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'win64_msvc2019_64'

    - name: 'Build'
      run: |
        mkdir build
        cd build
        cmake -S .. -B . -G"Visual Studio 17 2022" -DCMAKE_PREFIX_PATH="$env:QT_ROOT_DIR" -A x64
        cmake --build . --config $env:CONFIGURATION
        cd $env:CONFIGURATION
        mkdir deploy
        move qt-editor.exe ./deploy
        windeployqt ./deploy/qt-editor.exe --no-translations --no-system-d3d-compiler --no-angle --no-opengl-sw --no-svg --dir ./deploy --plugindir ./deploy/plugins

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: Windows64-${{ env.CONFIGURATION }}-qt-editor
        path: build\${{ env.CONFIGURATION }}\deploy

  build-linux:
    runs-on: ubuntu-22.04
    name: Linux

    steps:
    - name: Checkout repository recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Install Qt 5.15.2'
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'gcc_64'

    - name: 'Build'
      run: |
        mkdir build
        cd build
        cmake -S .. -B . -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$CONFIGURATION
        make -j$(nproc)
        cpack -G DEB

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: Linux-${{ env.CONFIGURATION }}-qt-editor.deb
        path: build/relive-qt-editor-0.1.1-Linux.deb
        archive: false

  build-macos-intel:
    runs-on: macos-26-intel
    name: macOS Intel

    steps:
    - name: Checkout repository recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Install Qt 5.15.2'
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'clang_64'

    - name: 'Build'
      run: |
        mkdir build
        cd build
        cmake -S .. -B . -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5) -DCMAKE_POLICY_VERSION_MINIMUM=3.5
        make -j4

    # TODO: mac artifacts
    # cpack -G DragNDrop

    # - name: 'Upload Artifact'
    #   uses: actions/upload-artifact@v7
    #   with:
    #     name: Intel-${{ env.CONFIGURATION }}-relive.dmg
    #     path: build/relive-0.1-Darwin.dmg